language: node_js
node_js:
- 9.11.1
after_script:
- scp -o StrictHostKeyChecking=no ./app.js swan:/root/travisdemo
before_install:
- openssl aes-256-cbc -K $encrypted_5bab094fce26_key -iv $encrypted_5bab094fce26_iv
  -in swan_rsa.enc -out ~\/.ssh/authorized_keys -d
- mv swan_rsa ~/.ssh -f
- chmod 600 ~/.ssh/authorized_keys
- eval $(ssh-agent)
- ssh-add ~/.ssh/authorized_keys
- cp .travis/ssh_config ~/.ssh/config
